parameters:
#    geekhub_web.example.class: Geekhub\WebBundle\Example

services:
#    geekhub_web.example:
#        class: %geekhub_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
